### ISSUE TITLE
Ubuntu 23.04 support

### ISSUE THREAD

**Issue by GoodM4ven** [faissaloo/azan-gnome-shell-extension#12]
The extension is incompatible with the current Ubuntu version (23.04).

**Comment by AbdelrahmanElhosiny** [comment]
If you are using gnome 44.3 just edit metadata.json file by adding "44.3" to "shell-version", you can find the file in this dir: $HOME/.local/share/gnome-shell/extensions/azan@faissal.bensefia.id
