### ISSUE TITLE
Incompatiblity with current GNOME version

### ISSUE THREAD

**Issue by C0d3rZ3r0** [faissaloo/azan-gnome-shell-extension#7]
I updated to Ubuntu 22.04 LTS from 20.04. It broke this GNOME extension.

Here is what the extension manager shows:

![image](https://user-images.githubusercontent.com/10358359/185567082-febd6ca4-29d4-44db-b98a-af12922bced5.png)

My Ubuntu and GNOME versions:

```
user@host:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

user@host:~$ gnome-shell --version
GNOME Shell 42.2

user@host:~$ 
```

**Comment by faissaloo** [comment]
Probably just needs a tweak to the metadata, I don't really use Gnome anymore but I'll look into it inshallah

**Comment by faissaloo** [comment]
Should be sorted now inshallah
